export type Country = {
  code: string;
  dial: string;
  name: string;
};

const RAW: Country[] = [
  { code: "AF", dial: "+93", name: "Afganistan" },
  { code: "ZA", dial: "+27", name: "Africa de Sud" },
  { code: "AL", dial: "+355", name: "Albania" },
  { code: "DZ", dial: "+213", name: "Algeria" },
  { code: "AD", dial: "+376", name: "Andorra" },
  { code: "AO", dial: "+244", name: "Angola" },
  { code: "AI", dial: "+1264", name: "Anguilla" },
  { code: "AG", dial: "+1268", name: "Antigua și Barbuda" },
  { code: "SA", dial: "+966", name: "Arabia Saudită" },
  { code: "AR", dial: "+54", name: "Argentina" },
  { code: "AM", dial: "+374", name: "Armenia" },
  { code: "AW", dial: "+297", name: "Aruba" },
  { code: "AU", dial: "+61", name: "Australia" },
  { code: "AT", dial: "+43", name: "Austria" },
  { code: "AZ", dial: "+994", name: "Azerbaidjan" },
  { code: "BS", dial: "+1242", name: "Bahamas" },
  { code: "BH", dial: "+973", name: "Bahrain" },
  { code: "BD", dial: "+880", name: "Bangladesh" },
  { code: "BB", dial: "+1246", name: "Barbados" },
  { code: "BY", dial: "+375", name: "Belarus" },
  { code: "BE", dial: "+32", name: "Belgia" },
  { code: "BZ", dial: "+501", name: "Belize" },
  { code: "BJ", dial: "+229", name: "Benin" },
  { code: "BM", dial: "+1441", name: "Bermuda" },
  { code: "BT", dial: "+975", name: "Bhutan" },
  { code: "BO", dial: "+591", name: "Bolivia" },
  { code: "BA", dial: "+387", name: "Bosnia și Herțegovina" },
  { code: "BW", dial: "+267", name: "Botswana" },
  { code: "BR", dial: "+55", name: "Brazilia" },
  { code: "BN", dial: "+673", name: "Brunei" },
  { code: "BG", dial: "+359", name: "Bulgaria" },
  { code: "BF", dial: "+226", name: "Burkina Faso" },
  { code: "BI", dial: "+257", name: "Burundi" },
  { code: "KH", dial: "+855", name: "Cambodgia" },
  { code: "CM", dial: "+237", name: "Camerun" },
  { code: "CA", dial: "+1", name: "Canada" },
  { code: "CV", dial: "+238", name: "Capul Verde" },
  { code: "CZ", dial: "+420", name: "Cehia" },
  { code: "CL", dial: "+56", name: "Chile" },
  { code: "CN", dial: "+86", name: "China" },
  { code: "TD", dial: "+235", name: "Ciad" },
  { code: "CY", dial: "+357", name: "Cipru" },
  { code: "CI", dial: "+225", name: "Coasta de Fildeș" },
  { code: "CO", dial: "+57", name: "Columbia" },
  { code: "KM", dial: "+269", name: "Comore" },
  { code: "KP", dial: "+850", name: "Coreea de Nord" },
  { code: "KR", dial: "+82", name: "Coreea de Sud" },
  { code: "CR", dial: "+506", name: "Costa Rica" },
  { code: "HR", dial: "+385", name: "Croația" },
  { code: "CU", dial: "+53", name: "Cuba" },
  { code: "CW", dial: "+599", name: "Curaçao" },
  { code: "DK", dial: "+45", name: "Danemarca" },
  { code: "DJ", dial: "+253", name: "Djibouti" },
  { code: "DM", dial: "+1767", name: "Dominica" },
  { code: "EC", dial: "+593", name: "Ecuador" },
  { code: "EG", dial: "+20", name: "Egipt" },
  { code: "SV", dial: "+503", name: "El Salvador" },
  { code: "CH", dial: "+41", name: "Elveția" },
  { code: "AE", dial: "+971", name: "Emiratele Arabe Unite" },
  { code: "ER", dial: "+291", name: "Eritreea" },
  { code: "EE", dial: "+372", name: "Estonia" },
  { code: "SZ", dial: "+268", name: "Eswatini" },
  { code: "ET", dial: "+251", name: "Etiopia" },
  { code: "FJ", dial: "+679", name: "Fiji" },
  { code: "PH", dial: "+63", name: "Filipine" },
  { code: "FI", dial: "+358", name: "Finlanda" },
  { code: "FR", dial: "+33", name: "Franța" },
  { code: "GA", dial: "+241", name: "Gabon" },
  { code: "GM", dial: "+220", name: "Gambia" },
  { code: "GE", dial: "+995", name: "Georgia" },
  { code: "DE", dial: "+49", name: "Germania" },
  { code: "GH", dial: "+233", name: "Ghana" },
  { code: "GI", dial: "+350", name: "Gibraltar" },
  { code: "GR", dial: "+30", name: "Grecia" },
  { code: "GD", dial: "+1473", name: "Grenada" },
  { code: "GL", dial: "+299", name: "Groenlanda" },
  { code: "GP", dial: "+590", name: "Guadelupa" },
  { code: "GU", dial: "+1671", name: "Guam" },
  { code: "GT", dial: "+502", name: "Guatemala" },
  { code: "GG", dial: "+44", name: "Guernsey" },
  { code: "GN", dial: "+224", name: "Guineea" },
  { code: "GQ", dial: "+240", name: "Guineea Ecuatorială" },
  { code: "GW", dial: "+245", name: "Guineea-Bissau" },
  { code: "GY", dial: "+592", name: "Guyana" },
  { code: "GF", dial: "+594", name: "Guyana Franceză" },
  { code: "HT", dial: "+509", name: "Haiti" },
  { code: "HN", dial: "+504", name: "Honduras" },
  { code: "HK", dial: "+852", name: "Hong Kong" },
  { code: "IN", dial: "+91", name: "India" },
  { code: "ID", dial: "+62", name: "Indonezia" },
  { code: "CX", dial: "+61", name: "Insula Christmas" },
  { code: "IM", dial: "+44", name: "Insula Man" },
  { code: "NF", dial: "+672", name: "Insula Norfolk" },
  { code: "KY", dial: "+1345", name: "Insulele Cayman" },
  { code: "CC", dial: "+61", name: "Insulele Cocos" },
  { code: "CK", dial: "+682", name: "Insulele Cook" },
  { code: "FK", dial: "+500", name: "Insulele Falkland" },
  { code: "FO", dial: "+298", name: "Insulele Feroe" },
  { code: "MP", dial: "+1670", name: "Insulele Mariane de Nord" },
  { code: "MH", dial: "+692", name: "Insulele Marshall" },
  { code: "PN", dial: "+64", name: "Insulele Pitcairn" },
  { code: "SB", dial: "+677", name: "Insulele Solomon" },
  { code: "TC", dial: "+1649", name: "Insulele Turks și Caicos" },
  { code: "VI", dial: "+1340", name: "Insulele Virgine Americane" },
  { code: "VG", dial: "+1284", name: "Insulele Virgine Britanice" },
  { code: "JO", dial: "+962", name: "Iordania" },
  { code: "IQ", dial: "+964", name: "Irak" },
  { code: "IR", dial: "+98", name: "Iran" },
  { code: "IE", dial: "+353", name: "Irlanda" },
  { code: "IS", dial: "+354", name: "Islanda" },
  { code: "IL", dial: "+972", name: "Israel" },
  { code: "IT", dial: "+39", name: "Italia" },
  { code: "JM", dial: "+1876", name: "Jamaica" },
  { code: "JP", dial: "+81", name: "Japonia" },
  { code: "JE", dial: "+44", name: "Jersey" },
  { code: "KZ", dial: "+7", name: "Kazahstan" },
  { code: "KG", dial: "+996", name: "Kârgâzstan" },
  { code: "KE", dial: "+254", name: "Kenya" },
  { code: "KI", dial: "+686", name: "Kiribati" },
  { code: "XK", dial: "+383", name: "Kosovo" },
  { code: "KW", dial: "+965", name: "Kuwait" },
  { code: "LA", dial: "+856", name: "Laos" },
  { code: "LS", dial: "+266", name: "Lesotho" },
  { code: "LV", dial: "+371", name: "Letonia" },
  { code: "LB", dial: "+961", name: "Liban" },
  { code: "LR", dial: "+231", name: "Liberia" },
  { code: "LY", dial: "+218", name: "Libia" },
  { code: "LI", dial: "+423", name: "Liechtenstein" },
  { code: "LT", dial: "+370", name: "Lituania" },
  { code: "LU", dial: "+352", name: "Luxemburg" },
  { code: "MO", dial: "+853", name: "Macao" },
  { code: "MK", dial: "+389", name: "Macedonia de Nord" },
  { code: "MG", dial: "+261", name: "Madagascar" },
  { code: "MY", dial: "+60", name: "Malaezia" },
  { code: "MW", dial: "+265", name: "Malawi" },
  { code: "MV", dial: "+960", name: "Maldive" },
  { code: "ML", dial: "+223", name: "Mali" },
  { code: "MT", dial: "+356", name: "Malta" },
  { code: "MA", dial: "+212", name: "Maroc" },
  { code: "MQ", dial: "+596", name: "Martinica" },
  { code: "MR", dial: "+222", name: "Mauritania" },
  { code: "MU", dial: "+230", name: "Mauritius" },
  { code: "YT", dial: "+262", name: "Mayotte" },
  { code: "MX", dial: "+52", name: "Mexic" },
  { code: "FM", dial: "+691", name: "Micronezia" },
  { code: "MC", dial: "+377", name: "Monaco" },
  { code: "MN", dial: "+976", name: "Mongolia" },
  { code: "MS", dial: "+1664", name: "Montserrat" },
  { code: "MZ", dial: "+258", name: "Mozambic" },
  { code: "ME", dial: "+382", name: "Muntenegru" },
  { code: "MM", dial: "+95", name: "Myanmar" },
  { code: "NA", dial: "+264", name: "Namibia" },
  { code: "NR", dial: "+674", name: "Nauru" },
  { code: "NP", dial: "+977", name: "Nepal" },
  { code: "NI", dial: "+505", name: "Nicaragua" },
  { code: "NE", dial: "+227", name: "Niger" },
  { code: "NG", dial: "+234", name: "Nigeria" },
  { code: "NU", dial: "+683", name: "Niue" },
  { code: "NO", dial: "+47", name: "Norvegia" },
  { code: "NC", dial: "+687", name: "Noua Caledonie" },
  { code: "NZ", dial: "+64", name: "Noua Zeelandă" },
  { code: "OM", dial: "+968", name: "Oman" },
  { code: "PK", dial: "+92", name: "Pakistan" },
  { code: "PW", dial: "+680", name: "Palau" },
  { code: "PS", dial: "+970", name: "Palestina" },
  { code: "PA", dial: "+507", name: "Panama" },
  { code: "PG", dial: "+675", name: "Papua Noua Guinee" },
  { code: "PY", dial: "+595", name: "Paraguay" },
  { code: "PE", dial: "+51", name: "Peru" },
  { code: "PF", dial: "+689", name: "Polinezia Franceză" },
  { code: "PL", dial: "+48", name: "Polonia" },
  { code: "PT", dial: "+351", name: "Portugalia" },
  { code: "PR", dial: "+1787", name: "Puerto Rico" },
  { code: "QA", dial: "+974", name: "Qatar" },
  { code: "GB", dial: "+44", name: "Regatul Unit" },
  { code: "CF", dial: "+236", name: "Republica Centrafricană" },
  { code: "CG", dial: "+242", name: "Republica Congo" },
  { code: "CD", dial: "+243", name: "Republica Democratică Congo" },
  { code: "DO", dial: "+1809", name: "Republica Dominicană" },
  { code: "MD", dial: "+373", name: "Republica Moldova" },
  { code: "RE", dial: "+262", name: "Réunion" },
  { code: "RO", dial: "+40", name: "România" },
  { code: "RU", dial: "+7", name: "Rusia" },
  { code: "RW", dial: "+250", name: "Rwanda" },
  { code: "EH", dial: "+212", name: "Sahara Occidentală" },
  { code: "BL", dial: "+590", name: "Saint Barthélemy" },
  { code: "PM", dial: "+508", name: "Saint Pierre și Miquelon" },
  { code: "WS", dial: "+685", name: "Samoa" },
  { code: "AS", dial: "+1684", name: "Samoa Americană" },
  { code: "SM", dial: "+378", name: "San Marino" },
  { code: "ST", dial: "+239", name: "São Tomé și Príncipe" },
  { code: "SN", dial: "+221", name: "Senegal" },
  { code: "RS", dial: "+381", name: "Serbia" },
  { code: "SC", dial: "+248", name: "Seychelles" },
  { code: "SH", dial: "+290", name: "Sfânta Elena" },
  { code: "LC", dial: "+1758", name: "Sfânta Lucia" },
  { code: "KN", dial: "+1869", name: "Sfântul Kitts și Nevis" },
  { code: "MF", dial: "+590", name: "Sfântul Martin (Franceză)" },
  { code: "SX", dial: "+1721", name: "Sfântul Martin (Olandeză)" },
  { code: "VC", dial: "+1784", name: "Sfântul Vincent și Grenadinele" },
  { code: "SL", dial: "+232", name: "Sierra Leone" },
  { code: "SG", dial: "+65", name: "Singapore" },
  { code: "SY", dial: "+963", name: "Siria" },
  { code: "SK", dial: "+421", name: "Slovacia" },
  { code: "SI", dial: "+386", name: "Slovenia" },
  { code: "SO", dial: "+252", name: "Somalia" },
  { code: "ES", dial: "+34", name: "Spania" },
  { code: "LK", dial: "+94", name: "Sri Lanka" },
  { code: "US", dial: "+1", name: "Statele Unite" },
  { code: "SD", dial: "+249", name: "Sudan" },
  { code: "SS", dial: "+211", name: "Sudanul de Sud" },
  { code: "SE", dial: "+46", name: "Suedia" },
  { code: "SR", dial: "+597", name: "Surinam" },
  { code: "SJ", dial: "+47", name: "Svalbard și Jan Mayen" },
  { code: "TJ", dial: "+992", name: "Tadjikistan" },
  { code: "TW", dial: "+886", name: "Taiwan" },
  { code: "TZ", dial: "+255", name: "Tanzania" },
  { code: "IO", dial: "+246", name: "Teritoriul Britanic din Oceanul Indian" },
  { code: "TH", dial: "+66", name: "Thailanda" },
  { code: "TL", dial: "+670", name: "Timorul de Est" },
  { code: "TG", dial: "+228", name: "Togo" },
  { code: "TK", dial: "+690", name: "Tokelau" },
  { code: "TO", dial: "+676", name: "Tonga" },
  { code: "TT", dial: "+1868", name: "Trinidad și Tobago" },
  { code: "TN", dial: "+216", name: "Tunisia" },
  { code: "TR", dial: "+90", name: "Turcia" },
  { code: "TM", dial: "+993", name: "Turkmenistan" },
  { code: "TV", dial: "+688", name: "Tuvalu" },
  { code: "UA", dial: "+380", name: "Ucraina" },
  { code: "UG", dial: "+256", name: "Uganda" },
  { code: "HU", dial: "+36", name: "Ungaria" },
  { code: "UY", dial: "+598", name: "Uruguay" },
  { code: "UZ", dial: "+998", name: "Uzbekistan" },
  { code: "VU", dial: "+678", name: "Vanuatu" },
  { code: "VA", dial: "+39", name: "Vatican" },
  { code: "VE", dial: "+58", name: "Venezuela" },
  { code: "VN", dial: "+84", name: "Vietnam" },
  { code: "WF", dial: "+681", name: "Wallis și Futuna" },
  { code: "YE", dial: "+967", name: "Yemen" },
  { code: "ZM", dial: "+260", name: "Zambia" },
  { code: "ZW", dial: "+263", name: "Zimbabwe" },
  { code: "NL", dial: "+31", name: "Țările de Jos" },
];

export const COUNTRIES: Country[] = [...RAW].sort((a, b) =>
  a.name.localeCompare(b.name, "ro"),
);

export function flagEmoji(code: string): string {
  const upper = code.toUpperCase();
  if (upper.length !== 2) return "\u{1F3F3}";
  const OFFSET = 0x1f1e6 - 65;
  return String.fromCodePoint(
    OFFSET + upper.charCodeAt(0),
    OFFSET + upper.charCodeAt(1),
  );
}

export function normalizeForSearch(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "");
}
